image: node:8.12.0

pages:
  cache:
    paths:
    - node_modules/

  stage: deploy
  script:
  - npm install -g @angular/cli@latest
  - npm install
  - ng build
  - mkdir -p public
  - mv dist/shoook/* public/
  environment:
    name: staging
    url: https://staging.shoook.com
  artifacts:
    paths:
    - public
  only:
  - master
  - pages