image: node:8.12.0

pages:
  cache:
    paths:
    - node_modules/

  stage: deploy
  script:
  - npm install -g @angular/cli@latest
  - npm install
  - ng build --base-href /myUrl/
  - mkdir -p public
  - mv dist/shoook/* public/
  artifacts:
    paths:
    - public
  only:
  - master
  - pages